pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                buildDebug()
            }
        }
        stage('Run Unit Tests') {
            steps {
                runUnitTests()
            }
        }
    }
}

def buildDebug() {
    sh "./gradlew clean assembleDebug"
    archiveArtifacts artifacts: 'app/build/outputs/apk/demo/debug/*.apk', fingerprint: true
}

def runUnitTests() {
    sh "./gradlew testDebugUnitTest"
    junit allowEmptyResults: true, testResults: '**/test-results/*.xml'
}
