pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh './gradlew clean assembleDebug'
                archiveArtifacts artifacts: 'app/build/outputs/apk/demo/debug/*.apk', fingerprint: true
            }
        }
        stage('Unit Tests') {
            steps {
                sh './gradlew testDemoDebugUnitTest -Proborazzi.test.verify=false'
                junit 'app/build/reports/tests/**/*'
            }
        }
    }
}
