pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh "./gradlew clean assembleDebug"
                    archiveArtifacts
                        artifacts: 'app/build/outputs/apk/demo/debug/*.apk',
                        fingerprint: true,
            }
        }
        stage('Unit Tests') {
            steps {
                // Запускаем unit-тесты и генерируем отчёты
                sh './gradlew clean testDebugUnitTest'

                // Сохраняем отчёты в Jenkins
                junit '**/build/test-results/testDebugUnitTest/*.xml'
                archiveArtifacts '**/build/reports/tests/testDebugUnitTest/**/*'
            }
        }
        stage('Publish HTML Report') {
            steps {
                // Публикуем HTML-отчёт (требуется плагин "HTML Publisher")
                publishHTML(
                    target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'app/build/reports/tests/testDebugUnitTest',
                        reportFiles: 'index.html',
                        reportName: 'JUnit 4 Test Report'
                    ]
                )
            }
        }
    }
}
